# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrix2vector <- function(m, byrow = FALSE) {
    .Call('_PPtreeCluster_matrix2vector', PACKAGE = 'PPtreeCluster', m, byrow)
}

Quantile <- function(x, probs) {
    .Call('_PPtreeCluster_Quantile', PACKAGE = 'PPtreeCluster', x, probs)
}

.HolesIndex1D <- function(origdata, proj = numeric(0)) {
    .Call('_PPtreeCluster_HolesIndex1D', PACKAGE = 'PPtreeCluster', origdata, proj)
}

.SkewIndex1D <- function(origdata, proj = numeric(0)) {
    .Call('_PPtreeCluster_SkewIndex1D', PACKAGE = 'PPtreeCluster', origdata, proj)
}

.CombIndex1D <- function(origdata, proj = numeric(0), gamma = 0.5) {
    .Call('_PPtreeCluster_CombIndex1D', PACKAGE = 'PPtreeCluster', origdata, proj, gamma)
}

.LppIndex1D <- function(origdata, proj = numeric(0), method = "kNN", eps = 0, probV = numeric(0.05), weight = FALSE, nk = 0L, t = 1.0) {
    .Call('_PPtreeCluster_LppIndex1D', PACKAGE = 'PPtreeCluster', origdata, proj, method, eps, probV, weight, nk, t)
}

.NHIndex1D <- function(origdata, proj = numeric(0), m = 0L) {
    .Call('_PPtreeCluster_NHIndex1D', PACKAGE = 'PPtreeCluster', origdata, proj, m)
}

.PIndex1D <- function(origdata, proj = numeric(0), probT = numeric(0.2), R = numeric(0.01)) {
    .Call('_PPtreeCluster_PIndex1D', PACKAGE = 'PPtreeCluster', origdata, proj, probT, R)
}

.PPclustopt1D <- function(origdata, PPmethod = "Holes", gamma = 0.9, method = "kNN", eps = 0, probV = numeric(0.2), weight = FALSE, nk = 0L, t = 1.0, m = 0L, probTV = numeric(0), RV = numeric(0), energy = 0, cooling = 0.999, TOL = 0.0001, maxiter = 50000L) {
    .Call('_PPtreeCluster_PPclustopt1D', PACKAGE = 'PPtreeCluster', origdata, PPmethod, gamma, method, eps, probV, weight, nk, t, m, probTV, RV, energy, cooling, TOL, maxiter)
}

